'use client';
import Link from 'next/link';
import { ArrowUpRight, Heart, ShoppingBag, Sparkles, Star, Truck, ShieldCheck } from 'lucide-react';
import { useState } from 'react';
export const products=[
{slug:'luna-boucle-sofa',name:'Luna Bouclé Sofa',price:89900,category:'Living',image:'/tovi/15d900d80767c34c4396197a2a935293.jpg',tag:'Bestseller',desc:'A generous, softly sculpted sofa designed for slow afternoons and long evenings.'},
{slug:'atelier-dining-collection',name:'Atelier Dining Collection',price:119000,category:'Dining',image:'/tovi/2c050b2da01e5ff74969aada972360db.jpg',tag:'New',desc:'Warm timber, elegant proportions and a table made for gathering.'},
{slug:'noir-bedroom-suite',name:'Noir Bedroom Suite',price:148500,category:'Bedroom',image:'/tovi/6def6def9e3064a1e6c7e1513df7ddb9.jpg',tag:'Signature',desc:'A calm bedroom composition with tactile layers and architectural presence.'},
{slug:'atelier-lounge-chair',name:'Atelier Lounge Chair',price:42900,category:'Living',image:'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1200&q=88',tag:'Edit',desc:'Curved comfort with a quiet sculptural silhouette.'},
{slug:'milo-console',name:'Milo Stone Console',price:64900,category:'Objects',image:'https://images.unsplash.com/photo-1618220179428-22790b461013?auto=format&fit=crop&w=1200&q=88',tag:'New',desc:'A restrained console for entryways, dining rooms and collected corners.'},
{slug:'sora-bedside',name:'Sora Bedside Table',price:28900,category:'Bedroom',image:'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=1200&q=88',tag:'Edit',desc:'Compact storage with soft edges and natural character.'}
];
export function Header(){return <header className="site-header"><Link href="/" className="brand"><span>VINCE</span><small>Maison · Furniture & Interiors</small></Link><nav className="main-nav"><Link href="/">Home</Link><Link href="/shop">Collection</Link><Link href="/spaces">Spaces</Link><Link href="/journal">Journal</Link><Link href="/concierge" className="gold">AI Concierge</Link></nav><div className="header-actions"><Link className="icon-button" href="/wishlist"><Heart size={17}/></Link><Link className="bag-link" href="/cart"><ShoppingBag size={17}/><span>Bag</span></Link></div></header>}
export function Footer(){return <footer><div className="footer-grid"><div><span className="footer-brand display">VINCE</span><p>Furniture, interiors and intelligent styling for beautiful living.</p></div><div><b>Explore</b><Link href="/shop">Collection</Link><Link href="/spaces">Spaces</Link><Link href="/journal">Journal</Link></div><div><b>Client care</b><Link href="/contact">Contact</Link><Link href="/account">Account</Link><Link href="/cart">Shopping bag</Link></div><div><b>Nairobi</b><p>Private appointments<br/>Kenya</p></div></div><div className="copyright">© 2026 VINCE Maison · Crafted for beautiful living</div></footer>}
export function PageShell({eyebrow,title,children}:{eyebrow:string,title:React.ReactNode,children:React.ReactNode}){return <main className="site-shell min-h-screen"><div className="marquee"><span>VINCE MAISON · NAIROBI · PRIVATE INTERIOR CONSULTATIONS · COMPLIMENTARY DELIVERY OVER KSh 20,000 · </span></div><Header/><section className="editorial-intro" style={{paddingTop:110,paddingBottom:75}}><div><p className="eyebrow">{eyebrow}</p></div><div><h1 className="display" style={{fontSize:'clamp(3.5rem,8vw,8rem)',lineHeight:.88,letterSpacing:'-.055em'}}>{title}</h1></div></section>{children}<Footer/></main>}
export function ProductCard({product}:{product:any}){const [liked,setLiked]=useState(false);return <article className="product-piece" style={{marginTop:0}}><Link href={`/product/${product.slug}`} className="product-image"><img src={product.image} alt={product.name}/><span className="piece-number">{product.tag}</span><button aria-label="Wishlist" onClick={(e)=>{e.preventDefault();setLiked(!liked)}} className="absolute right-3 top-3 rounded-full bg-black/40 p-2 text-white backdrop-blur"><Heart size={15} fill={liked?'currentColor':'none'}/></button><span className="product-view">View piece <ArrowUpRight size={13}/></span></Link><div className="product-info"><div><p className="product-cat">{product.category}</p><h3 className="display">{product.name}</h3></div><p className="price">KSh {product.price.toLocaleString()}</p></div></article>}
export function ServiceStrip(){return <section className="services"><div><Truck size={19}/><b>White-glove delivery</b><p>Careful delivery and placement across Kenya.</p></div><div><ShieldCheck size={19}/><b>Secure shopping</b><p>Protected checkout and customer information.</p></div><div><Sparkles size={19}/><b>Private styling</b><p>Personal guidance for your space, taste and budget.</p></div></section>}
export function Stars(){return <div className="flex items-center gap-1 text-[var(--gold)]">{[1,2,3,4,5].map(i=><Star key={i} size={13} fill="currentColor"/>)}<span className="ml-2 text-xs text-[var(--muted)]">4.9 / 5</span></div>}
