'use client';
import Link from 'next/link';
import { ArrowUpRight, Heart, ShoppingBag, Sparkles, Star, Truck, ShieldCheck, MessageCircle, Mail } from 'lucide-react';
import { useEffect, useState } from 'react';
import type { Product } from '../data/products';

const BAG_KEY='kbyusuf_quote_bag';
export function Header(){const [count,setCount]=useState(0);useEffect(()=>{const load=()=>{try{const items=JSON.parse(localStorage.getItem(BAG_KEY)||'[]');setCount(items.reduce((s:number,i:{quantity:number})=>s+i.quantity,0))}catch{setCount(0)}};load();window.addEventListener('kbyusuf-bag-updated',load);window.addEventListener('storage',load);return()=>{window.removeEventListener('kbyusuf-bag-updated',load);window.removeEventListener('storage',load)}},[]);return <header className="site-header"><Link href="/" className="brand"><span>KB YUSUF FURNITURE</span><small>Interior Decorations · Furniture</small></Link><nav className="main-nav"><Link href="/">Home</Link><Link href="/shop">Collection</Link><Link href="/spaces">Spaces</Link><Link href="/journal">Journal</Link><Link href="/contact" className="gold">Design Services</Link></nav><div className="header-actions"><Link className="icon-button" href="/wishlist"><Heart size={17}/></Link><Link className="bag-link" href="/cart" aria-label={`Request bag${count?`, ${count} pieces`:''}`}><ShoppingBag size={17}/><span>Bag{count>0&&` · ${count}`}</span></Link></div></header>}
export function FloatingContacts(){return <div className="floating-contacts" aria-label="Contact KB Yusuf Furniture"><a className="floating-contact whatsapp" href="https://wa.me/2348109730941" target="_blank" rel="noreferrer" aria-label="Chat on WhatsApp"><MessageCircle size={18}/><span>WhatsApp</span></a><a className="floating-contact email" href="mailto:kbyusufurniture@gmail.com" aria-label="Email KB Yusuf Furniture"><Mail size={18}/><span>Email</span></a></div>}
export function Footer(){return <footer><div className="footer-grid"><div><span className="footer-brand display">KB YUSUF FURNITURE</span><p>Furniture and interior decorations for beautiful living.</p></div><div><b>Explore</b><Link href="/shop">Collection</Link><Link href="/spaces">Spaces</Link><Link href="/journal">Journal</Link></div><div><b>Client care</b><Link href="/contact">Contact</Link><Link href="/account">Account</Link><Link href="/cart">Shopping bag</Link></div><div><b>Abuja, Nigeria</b><p>+234 810 973 0941<br/>kbyusufurniture@gmail.com</p></div></div><div className="copyright">© 2026 KB Yusuf Furniture International Limited · Interior Decorations · Abuja, Nigeria</div></footer>}
export function PageShell({eyebrow,title,children}:{eyebrow:string,title:React.ReactNode,children:React.ReactNode}){return <main className="site-shell min-h-screen"><div className="marquee"><span>KB YUSUF FURNITURE INTERNATIONAL LIMITED · ABUJA, NIGERIA · INTERIOR DECORATIONS · COMPLIMENTARY DELIVERY · </span></div><Header/><section className="editorial-intro" style={{paddingTop:110,paddingBottom:75}}><div><p className="eyebrow">{eyebrow}</p></div><div><h1 className="display" style={{fontSize:'clamp(3.5rem,8vw,8rem)',lineHeight:.88,letterSpacing:'-.055em'}}>{title}</h1></div></section>{children}<Footer/><FloatingContacts/></main>}
export function ProductCard({product}:{product:Product}){const [liked,setLiked]=useState(false);return <article className="product-piece" style={{marginTop:0}}><Link href={`/product/${product.slug}`} className="product-image"><img src={product.image} alt={product.name}/><span className="piece-number">{product.tag}</span><span className="product-view">View piece <ArrowUpRight size={13}/></span></Link><button aria-label={`Add ${product.name} to wishlist`} onClick={()=>setLiked(!liked)} className="absolute right-3 top-3 z-10 rounded-full bg-black/40 p-2 text-white backdrop-blur"><Heart size={15} fill={liked?'currentColor':'none'}/></button><div className="product-info"><div><p className="product-cat">{product.category}</p><h3 className="display">{product.name}</h3></div></div></article>}
export function ServiceStrip(){return <section className="services"><div><Truck size={19}/><b>Delivery & placement</b><p>Careful delivery and placement for your furniture.</p></div><div><ShieldCheck size={19}/><b>Secure shopping</b><p>Protected customer information and quotation requests.</p></div><div><Sparkles size={19}/><b>Interior decoration</b><p>Professional guidance for your space, taste and budget.</p></div></section>}
export function Stars(){return <div className="flex items-center gap-1 text-[var(--gold)]">{[1,2,3,4,5].map(i=><Star key={i} size={13} fill="currentColor"/>)}<span className="ml-2 text-xs text-[var(--muted)]">4.9 / 5</span></div>}
