import Link from 'next/link';
import { ArrowRight, ArrowUpRight, Search, ShoppingBag, Sparkles, Truck, ShieldCheck, Heart } from 'lucide-react';
import ThemeToggle from './components/theme-toggle';
import ScrollProgress from './components/scroll-progress';
import PremiumPolish from './components/premium-polish';
import { furnitureImage, furnitureImages } from './data/images';

const images={hero:furnitureImage(1),living:furnitureImage(2),dining:furnitureImage(3),bedroom:furnitureImage(4),office:furnitureImage(5),lounge:furnitureImage(6),detail:furnitureImage(7),diningAlt:furnitureImage(8),bedroomAlt:furnitureImage(9)};
const products=[['Luna Bouclé Sofa','Living',furnitureImage(10),'luna-boucle-sofa'],['Atelier Dining Collection','Dining',furnitureImage(11),'atelier-dining-collection'],['Noir Bedroom Suite','Bedroom',furnitureImage(12),'noir-bedroom-suite']];
const inspiration=[['Living / Soft architecture',furnitureImage(13)],['Dining / Sculptural forms',furnitureImage(14)],['Bedroom / Quiet materials',furnitureImage(15)],['Workspace / Warm minimalism',furnitureImage(16)],['Objects / Natural texture',furnitureImage(17)]];

export default function Home(){return <main className="site-shell min-h-screen overflow-hidden"><ScrollProgress/><PremiumPolish/>
<div className="marquee"><span>KB YUSUF FURNITURE INTERNATIONAL LIMITED · ABUJA, NIGERIA · INTERIOR DECORATIONS · COMPLIMENTARY DELIVERY · KB YUSUF FURNITURE INTERNATIONAL LIMITED · ABUJA, NIGERIA · INTERIOR DECORATIONS · COMPLIMENTARY DELIVERY · </span></div>
<header className="site-header"><Link href="/" className="brand"><span>KB YUSUF FURNITURE</span><small>Interior Decorations · Furniture</small></Link><nav className="main-nav"><Link href="/" className="nav-link active">Home</Link><Link href="/shop" className="nav-link">Collection</Link><Link href="/spaces" className="nav-link">Spaces</Link><Link href="/journal" className="nav-link">Journal</Link><Link href="/concierge" className="nav-link gold">AI Concierge</Link></nav><div className="header-actions"><Link className="icon-button" href="/shop" aria-label="Search"><Search size={17}/></Link><Link className="icon-button" href="/wishlist" aria-label="Wishlist"><Heart size={17}/></Link><Link className="bag-link" href="/cart"><ShoppingBag size={17}/><span>Bag</span></Link><ThemeToggle/></div></header>
<section className="hero-premium"><img src={images.hero} alt="KB Yusuf Furniture interior collection"/><div className="hero-shade"/><div className="hero-content"><div className="hero-meta"><p>Collection No. 01 / 2026</p><p>Abuja<br/>Nigeria</p></div><div className="hero-bottom"><p className="eyebrow light">Furniture · Interior Decorations</p><h1 className="display hero-title">Live<br/><i>beautifully.</i></h1><div className="hero-actions"><p>Beautiful furniture and interior decorations, selected to bring comfort, character and lasting style to your space.</p><div className="button-row"><Link href="/shop" className="btn-gold">Explore collection <ArrowUpRight size={14}/></Link><Link href="/spaces" className="btn-ghost">Explore spaces</Link></div></div></div><div className="hero-foot"><span>Abuja · Nigeria</span></div></div></section>
<section className="editorial-intro"><div className="intro-label"><p className="eyebrow">KB Yusuf Furniture International Limited</p></div><div><h2 className="display">Beautiful spaces.<br/><i>Thoughtfully decorated.</i></h2><p>We provide furniture and interior decoration solutions that balance comfort, quality and character — helping homes and spaces feel complete.</p><Link href="/contact" className="gold-link">Contact our team <ArrowRight size={14}/></Link></div></section>
<section className="rooms-section"><div className="section-head"><div><p className="eyebrow">01 — The rooms</p><h2 className="display">Choose your atmosphere.</h2></div><Link href="/spaces" className="muted-link">View all spaces →</Link></div><div className="space-grid"><Link href="/shop?category=Living" className="space-card space-tall"><img src={images.living} alt="Living room collection"/><div className="space-overlay"/><div className="space-copy"><span>01 / Living</span><h3 className="display">The living room</h3><p>Sofas · lounge · occasional tables</p></div></Link><Link href="/shop?category=Dining" className="space-card"><img src={images.dining} alt="Dining collection"/><div className="space-overlay"/><div className="space-copy"><span>02 / Dining</span><h3 className="display">Gather</h3><p>Tables · chairs · lighting</p></div></Link><Link href="/shop?category=Bedroom" className="space-card"><img src={images.bedroom} alt="Bedroom collection"/><div className="space-overlay"/><div className="space-copy"><span>03 / Bedroom</span><h3 className="display">Unwind</h3><p>Beds · textiles · storage</p></div></Link><Link href="/concierge" className="space-card space-ai"><Sparkles size={20}/><div><span>04 / Interior styling</span><h3 className="display">Your room,<br/><i>carefully decorated.</i></h3><p>Tell us your space, taste and budget. Our team will help you build a considered edit.</p><b>Start a conversation →</b></div></Link></div></section>
<section className="inspiration-section"><div className="section-head"><div><p className="eyebrow">02 — The inspiration edit</p><h2 className="display">Beautiful, considered, collected.</h2></div></div><div className="masonry">{inspiration.map(([title,img],i)=><Link href="/journal" className={`inspiration-card insp-${i+1}`} key={title}><img src={img} alt={title}/><div><span>{title}</span><ArrowUpRight size={14}/></div></Link>)}</div><p className="image-note">KB Yusuf Furniture International Limited collection photography.</p></section>
<section className="products-section"><div className="section-head"><div><p className="eyebrow">03 — The edit</p><h2 className="display">Pieces with presence.</h2></div><Link href="/shop" className="muted-link">Shop all →</Link></div><div className="product-showcase">{products.map(([name,cat,img,slug],i)=><Link href={`/product/${slug}`} className={`product-piece piece-${i+1}`} key={name}><div className="product-image"><img src={img} alt={name}/><span className="piece-number">0{i+1}</span><span className="product-view">View piece <ArrowUpRight size={13}/></span></div><div className="product-info"><div><p className="product-cat">{cat}</p><h3 className="display">{name}</h3></div></div></Link>)}</div></section>
<section className="collection-archive"><div className="section-head"><div><p className="eyebrow">04 — Complete image collection</p><h2 className="display">Every piece. <i>One visual language.</i></h2></div><Link href="/shop" className="muted-link">Explore collection →</Link></div><div className="collection-grid">{furnitureImages.map((src,i)=><Link href={`/shop#furniture-${String(i+1).padStart(2,'0')}`} className="collection-tile" id={`furniture-${String(i+1).padStart(2,'0')}`} key={src}><img src={src} alt={`KB Yusuf Furniture collection image ${i+1}`} loading="lazy" decoding="async"/><span>{String(i+1).padStart(2,'0')}</span></Link>)}</div><p className="image-note">The complete 56-image KB Yusuf Furniture collection supplied for this website. No external furniture imagery is used.</p></section>
<section className="statement"><div className="statement-word display">KB YUSUF</div><div className="statement-grid"><div><p className="eyebrow">05 — Our approach</p><h2 className="display">Designed to be lived in.<br/><i>Made to feel like home.</i></h2></div><div><p>We focus on furniture, materials and interior details that bring comfort and character into everyday spaces.</p><div className="gold-line"/><small>Furniture · Interior Decorations · Craft · Place</small></div></div></section>
<section className="ai-banner"><img src={images.lounge} alt="KB Yusuf Furniture interior styling consultation"/><div className="ai-overlay"/><div className="ai-content"><Sparkles size={22}/><p className="eyebrow">KB Yusuf Furniture Concierge</p><h2 className="display">Tell us how you want<br/><i>your home to feel.</i></h2><p>“Warm, modern, comfortable.” Start there. We'll help you shape the space.</p><Link href="/concierge" className="btn-gold">Talk to our team <ArrowUpRight size={14}/></Link></div></section>
<section className="services"><div><Truck size={19}/><b>Delivery & placement</b><p>Careful delivery and placement for your furniture.</p></div><div><ShieldCheck size={19}/><b>Secure shopping</b><p>Protected payments and customer information.</p></div><div><Sparkles size={19}/><b>Interior decoration</b><p>Professional guidance for your space, taste and budget.</p></div></section>
<footer><div className="footer-grid"><div><span className="footer-brand display">KB YUSUF FURNITURE</span><p>KB Yusuf Furniture International Limited — furniture and interior decorations.</p></div><div><b>Explore</b><Link href="/shop">Collection</Link><Link href="/spaces">Spaces</Link><Link href="/journal">Journal</Link></div><div><b>Client care</b><Link href="/contact">Contact</Link><Link href="/account">Account</Link><Link href="/cart">Shopping bag</Link></div><div><b>Abuja, Nigeria</b><p>+234 810 973 0941<br/>kbyusufurniture@gmail.com</p></div></div><div className="copyright">© 2026 KB Yusuf Furniture International Limited · Interior Decorations · Abuja, Nigeria</div></footer></main>}
